import java.util.*;

// ===================== CUSTOMER CLASS =====================
class Customer {
    private int customerId;
    private String name;
    private String address;
    private String phone;

    public Customer(int customerId, String name, String address, String phone) {
        this.customerId = customerId;
        this.name = name;
        this.address = address;
        this.phone = phone;
    }

    public int getCustomerId() { return customerId; }
    public String getName() { return name; }

    public void display() {
        System.out.println("Customer ID : " + customerId);
        System.out.println("Name        : " + name);
        System.out.println("Address     : " + address);
        System.out.println("Phone       : " + phone);
    }
}

// ===================== BILL ITEM CLASS =====================
class BillItem {
    private int units;
    private double rate;
    private double amount;

    public BillItem(int units, double rate) {
        this.units = units;
        this.rate = rate;
        this.amount = units * rate;
    }

    public double getAmount() {
        return amount;
    }

    public void display() {
        System.out.println("Units : " + units + " | Rate : " + rate + " | Amount : " + amount);
    }
}

// ===================== BILL CLASS =====================
class Bill {
    private int billId;
    private Customer customer;
    private List<BillItem> items;
    private double totalAmount;

    public Bill(int billId, Customer customer) {
        this.billId = billId;
        this.customer = customer;
        this.items = new ArrayList<>();
    }

    public void addItem(BillItem item) {
        items.add(item);
        totalAmount += item.getAmount();
    }

    public void displayBill() {
        System.out.println("\n========= ELECTRICITY BILL =========");
        System.out.println("Bill ID : " + billId);
        customer.display();

        System.out.println("\n--- Bill Details ---");
        for (BillItem item : items) {
            item.display();
        }

        System.out.println("------------------------------------");
        System.out.println("Total Amount : Rs. " + totalAmount);
        System.out.println("====================================\n");
    }
}

// ===================== EMPLOYEE CLASS =====================
class Employee {
    private int employeeId;
    private String name;
    private String designation;

    public Employee(int employeeId, String name, String designation) {
        this.employeeId = employeeId;
        this.name = name;
        this.designation = designation;
    }

    public void display() {
        System.out.println("Generated By : " + name + " (" + designation + ")");
    }
}

// ===================== BUSINESS LOGIC CLASS =====================
class BillService {

    public static Bill generateBill(int billId, Customer customer, int units) {
        Bill bill = new Bill(billId, customer);

        if (units <= 100) {
            bill.addItem(new BillItem(units, 1.5));
        } else if (units <= 300) {
            bill.addItem(new BillItem(100, 1.5));
            bill.addItem(new BillItem(units - 100, 2.5));
        } else if (units <= 500) {
            bill.addItem(new BillItem(100, 1.5));
            bill.addItem(new BillItem(200, 2.5));
            bill.addItem(new BillItem(units - 300, 4));
        } else {
            bill.addItem(new BillItem(100, 1.5));
            bill.addItem(new BillItem(200, 2.5));
            bill.addItem(new BillItem(200, 4));
            bill.addItem(new BillItem(units - 500, 6));
        }

        // Fixed charge
        bill.addItem(new BillItem(1, 50)); 

        return bill;
    }
}

// ===================== MAIN CLASS =====================
public class ElectricBillingSystem {

    static Scanner sc = new Scanner(System.in);
    static ArrayList<Customer> customers = new ArrayList<>();
    static int billCounter = 100;

    public static void main(String[] args) {

        int choice;

        do {
            System.out.println("====== ELECTRIC BILLING SYSTEM ======");
            System.out.println("1. Add Customer & Generate Bill");
            System.out.println("2. Exit");
            System.out.print("Enter choice: ");

            choice = sc.nextInt();

            switch (choice) {
                case 1:
                    generate();
                    break;
                case 2:
                    System.out.println("Thank you!");
                    break;
                default:
                    System.out.println("Invalid choice!");
            }

        } while (choice != 2);
    }

    // ===================== METHOD =====================
    static void generate() {

        System.out.print("Enter Customer ID: ");
        int id = sc.nextInt();
        sc.nextLine();

        System.out.print("Enter Name: ");
        String name = sc.nextLine();

        System.out.print("Enter Address: ");
        String address = sc.nextLine();

        System.out.print("Enter Phone: ");
        String phone = sc.nextLine();

        Customer customer = new Customer(id, name, address, phone);
        customers.add(customer);

        System.out.print("Enter Units Consumed: ");
        int units = sc.nextInt();

        Bill bill = BillService.generateBill(++billCounter, customer, units);

        Employee emp = new Employee(1, "Admin", "Billing Officer");

        bill.displayBill();
        emp.display();
    }
}